// <auto-generated />
namespace BestMovies.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Setbirthdayfieldasnullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Setbirthdayfieldasnullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201810281930078_Set birthday field as nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
